[project]
name = "odoo-addons-oca-edi-framework"
version = "19.0.20260421.1"
dependencies = [
    "odoo-addon-edi_component_oca==19.0.*",
    "odoo-addon-edi_core_oca==19.0.*",
    "odoo-addon-edi_queue_oca==19.0.*",
    "odoo-addon-edi_record_metadata_oca==19.0.*",
    "odoo-addon-edi_ubl_oca==19.0.*",
    "odoo-addon-edi_webservice_oca==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
