[project]
name = "odoo-addons-oca-crm"
version = "19.0.20260423.0"
dependencies = [
    "odoo-addon-crm_industry==19.0.*",
    "odoo-addon-crm_lead_code==19.0.*",
    "odoo-addon-crm_lead_to_task==19.0.*",
    "odoo-addon-crm_lead_vat==19.0.*",
    "odoo-addon-crm_partner_assign==19.0.*",
    "odoo-addon-crm_stage_probability==19.0.*",
    "odoo-addon-crm_won_restrict_per_stage==19.0.*",
    "odoo-addon-marketing_crm_partner==19.0.*",
    "odoo-addon-srm==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
