[project]
name = "odoo-addons-oca-timesheet"
version = "19.0.20260424.0"
dependencies = [
    "odoo-addon-hr_timesheet_day_week==19.0.*",
    "odoo-addon-hr_timesheet_task_required==19.0.*",
    "odoo-addon-hr_timesheet_task_stage==19.0.*",
    "odoo-addon-hr_timesheet_time_control==19.0.*",
    "odoo-addon-hr_timesheet_time_control_begin_end==19.0.*",
    "odoo-addon-sale_order_update_timesheet_price==19.0.*",
    "odoo-addon-sale_timesheet_line_exclude==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
